<?php 
$brands = $this->getBrands();
$featured = $this->getFeaturedBrands();
$media = $this->getImageMediaPath();
?>
<div class="owl-carousel owl-theme">
<?php foreach($featured as $_fbrand):?>
	<div class="item">
		<span>
				<?php if($_fbrand->getUrlKey()):?>
					<a href="<?php echo $this->getUrl('brand').$_fbrand->getUrlKey()?>">
				<?php else:?>
					<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
				<?php endif;?>
				<?php if($_fbrand->getLogo()):?>
					<img class="f-barnd-img" src="<?php echo $media.$_fbrand->getLogo() ?>" title="<?php echo $_fbrand->getName();?>" alt="<?php echo $_fbrand->getName();?>"
					/>
				<?php else:?>
				<span class="brand-title">
					<?php echo $_fbrand->getName();?>
				</span>
				<?php endif;?>
			</a>
		</span>
	</div>
<?php endforeach;?>
</div>
<script type="text/javascript">
      require([
        'jquery',
        'owl.carousel/owl.carousel.min'
      ], function ($) {
        $("#brand_slider .owl-carousel").owlCarousel({
          autoplay: true,
          autoplayTimeout: 5000,
          autoplayHoverPause: true,
          dots: true,
          margin: 0,
          navRewind: true,
          animateIn: 'fadeIn',
          animateOut: 'fadeOut',
          loop: true,
          responsive:{
		        0:{
		            items:1
		        },
		        600:{
		            items:3
		        },
		        1000:{
		            items:6
		        }
		    }
        });
      });
</script>
