<?php 
$brands = $this->getBrands();
$featured = $this->getFeaturedBrands();
$media = $this->getImageMediaPath();
?>
<?php foreach($featured as $_fbrand):?>
	<div class="brand">
		<span>
				<?php if($_fbrand->getUrlKey()):?>
					<a href="<?php echo $this->getUrl('brand').$_fbrand->getUrlKey()?>">
				<?php else:?>
					<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
				<?php endif;?>
				<?php if($_fbrand->getLogo()):?>
					<img class="f-barnd-img" src="<?php echo $media.$_fbrand->getLogo() ?>" width="150px" height="150px" title="<?php echo $_fbrand->getName();?>" alt="<?php echo $_fbrand->getName();?>"
					/>
				<?php else:?>
				<span class="brand-title">
					<?php echo $_fbrand->getName();?>
				</span>
				<?php endif;?>
			</a>
		</span>
	</div>
<?php endforeach;?>
</div>
