<?php
$cat = $this->getRequest()->getParam('cat', false);
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
if(!empty($cat)){
    $categoryWidgetCollection = $objectManager->create('Mobicommerce\Mobiadmin3\Model\Resource\Categorywidget\CollectionFactory');
    
    $widgets = $categoryWidgetCollection->create()
    ->addFieldToFilter('widget_category_id', $cat)->setOrder('widget_position','ASC')
    ->load();
}
else{    
	$storeid = $this->getRequest()->getParam('store');
	$id = $this->getRequest()->getParam('id');
	$model = $objectManager->create('Mobicommerce\Mobiadmin3\Model\Resource\Applications\CollectionFactory');
    $application =  $model->create()->addFieldToFilter('id',$id)->getData();
	$appCode = $application['0']['app_code'];
	$HomewidgetFactory = $objectManager->create('Mobicommerce\Mobiadmin3\Model\Resource\Widget\CollectionFactory');
	
    if(!empty($storeid))
    {
        $widgets = $HomewidgetFactory->create()->addFieldToFilter('widget_app_code',$appCode)
		->addFieldToFilter('widget_store_id',$storeid);     
    }
    else
    {
        $widgets = $HomewidgetFactory->create()->addFieldToFilter('widget_app_code',$appCode);
    }

	$widgets->setOrder('widget_position','ASC');
}

$canEditPosition = true;
$versionType = '002';
if(empty($cat)){
	$versionType = $application['0']['version_type'];
}

if(!in_array($versionType, ['001', '002']))
	$versionType = '001';

if($versionType == '001')
	$canEditPosition = false;
?>

<div class="content-widget-new grid">
	<p class="note"><?php echo __('Change the complete look and feel of the home page with widget system. Configure your images, banners, category and product slider directly from this widget page to give desired look and feel to home screen.'); ?></p>

	<section class="admin__page-section">
	    <div class="admin__page-section-content">
	        <div class="admin__page-section-item">
	            <div class="admin__page-section-item-content">
	                <table class="admin__table-secondary <?php if($canEditPosition): ?>widget_sortable_table<?php endif; ?>">
	                	<tr>
	                		<th><?php echo __('Widget Id'); ?></th>
	                		<th><?php echo __('Widget Name'); ?></th>
	                		<th><?php echo __('Widget Title'); ?></th>
	                		<th><?php echo __('Widget Type'); ?></th>
	                		<th><?php echo __('Status'); ?></th>
	                		<th><?php echo __('Position'); ?></th>
	                		<th><?php echo __('Action'); ?></th>
	                	</tr>
	                	<?php if(count($widgets)): ?>
	                		<?php $tabindex = 100; ?>
	                		<?php foreach($widgets as $_widget): ?>
	                			<?php $_widget_data = @unserialize($_widget->getWidgetData()); ?>
	                			<tr>
	                				<td><?php if($canEditPosition): ?><i class="icon-sortable-move"></i><?php endif; ?><?php echo $_widget->getWidgetId()?></td>
									<td><?php echo $_widget->getWidgetLabel()?></td>
									<td><?php echo $_widget_data['title']; ?></td>
									<td>
										<?php if($_widget->getWidgetCode() == 'widget_image_slider'): ?>
											<?php echo __('Image Slider')?>
										<?php elseif($_widget->getWidgetCode() == 'widget_product_slider'):?>
											<?php echo __('Product List')?>
										<?php elseif($_widget->getWidgetCode() == 'widget_category'):?>
											<?php echo __('Category')?>
										<?php elseif($_widget->getWidgetCode() == 'widget_image'):?>
											<?php echo __('Image')?>
										<?php elseif($_widget->getWidgetCode() == 'widget_html'):?>
											<?php echo __('HTML Content')?>
										<?php endif;?>
									</td>
									<td>
									<?php if($_widget->getWidgetStatus() == 1):?>
										<?php echo 'Enable'; ?>
									<?php else:?>
										<?php echo 'Disable'; ?>
									<?php endif;?>
									</td>
									<?php if($canEditPosition): ?>
										<td><input type="text" onchange="markWidgetChange();" name="widget_position[<?php echo $_widget->getWidgetId()?>]" class="input-text" value="<?php echo $_widget->getWidgetPosition()?>" style="width:50px;" tabindex="<?php echo $tabindex; ?>" /></td>
									<?php endif; ?>
									<td><a onclick="return editbuttonclick(this,event)"  href="<?php echo $this->getUrl('mobicommerce/widget/callwidget', [
											'cat'		  => $_widget->getWidgetCategoryId(),
											'widget_id'   => $_widget->getWidgetId(),
											'widget_code' => $_widget->getWidgetCode(),
											'isAjax'      => true,
											'cat' => $_widget->getWidgetCategoryId()
										]);
									?>"><?php echo __("Edit")?></a>
									<?php if($versionType == '002'): ?>
										| 
										<a href="<?php echo $this->getUrl('mobicommerce/widget/deletewidget', [
											'widget_id' => $_widget->getWidgetId(),
											'cat' => $_widget->getWidgetCategoryId()
										]); ?>" onclick="markWidgetChange(); return confirm('Are you sure?')"><?php echo __("Delete")?></a>
									<?php endif; ?>
									</td>
	                			</tr>
	                		<?php endforeach; ?>
	                	<?php endif; ?>
	                </table>
	            </div>
	        </div>
	    </div>
	</section>
</div>

<script type="text/javascript">
	require([
	    "jquery",
	    "jquery/ui"
	], function (jQuery) {
		jQuery(function() {
			initWidgetSortable();
		});
	});

	function initWidgetSortable()
	{
		try{
			if(jQuery('.widget_sortable_table tbody').length) {
				jQuery('.widget_sortable_table tbody').sortable({
				  	stop: function( event, ui ) {
				  		var _widget_counter = 1;
				  		jQuery('input[name^="widget_position"]').each(function() {
				  			jQuery(this).val(_widget_counter);
				  			jQuery(this).attr('tabindex', _widget_counter);
				  			_widget_counter++;
				  		});
				  	}
				});
			}
		}
		catch(e) {
			console.log('sortable not supported');
		}
	}
</script>