<?php
//$lang_code = "en_US";
$lang_code =$this->getRequest()->getParam('lang_code');
$myHelper = $this->helper('Mobicommerce\Mobiadmin3\Helper\Data');
$repeatlangarray = [];
?>
<?php /* @var $this Mage_Core_Block_Template */ ?>
<?php if ($websites = $myHelper->getWebsites()): ?>
<p class="switcher"><label for="store_switcher"><?php echo __('Choose Language:') ?></label>
<select name="store_switcher" id="store_switcher" onchange="return switchStore(this);">
    <?php foreach ($websites as $website): ?>
                
	    <?php 
        
        foreach ($website->getGroups() as $group): ?>
			<?php
            
            $stores = $group->getStores();
            
            foreach ($stores as $store): ?>
			    <?php 
				$storeid = $store->getStoreId();
                $store_lang_code = $myHelper->getStoreConfig()->getValue('general/locale/code', \Magento\Store\Model\ScopeInterface::SCOPE_STORE, $store->getId());
				?>
                <?php if(in_array($store_lang_code, $repeatlangarray)):?>
				<?php else:?>
					<option value="<?php echo $store_lang_code; ?>" <?php if($store_lang_code == $lang_code) echo 'selected' ?>><?php echo $myHelper->getLocaleLabel($store_lang_code);?></option>
				<?php endif;?>
				<?php $repeatlangarray[] = $store_lang_code;?>
			<?php endforeach; ?>
		<?php endforeach; ?>
	<?php endforeach;
    ?>
</select>

</p>
<script type="text/javascript">
    function switchStore(obj) {
        var storeParam = obj.value ? 'lang_code/' + obj.value + '/' : '';
        if (obj.switchParams) {
            storeParam += obj.switchParams;
        }
    <?php if ($this->getUseConfirm()): ?>
        if (confirm("<?php echo __('Please confirm site switching. All data that hasn\'t been saved will be lost.') ?>")) {
            setLocation('<?php echo $this->getSwitchUrl() ?>' + storeParam);
            return true;
        } else {
            obj.value = '<?php echo $this->getStoreId() ?>';
        }
        return false;
    <?php else: ?>
        setLocation('<?php echo $this->getSwitchUrl() ?>' + storeParam);
    <?php endif; ?>
    }
</script>
<?php endif; ?>
