<?php 
$applicationData = $this->getRegistry()->registry('application_data');
$applicationCode = $applicationData->getAppCode();
$applicationName = $applicationData->getAppName();
$applicationKey = $applicationData->getAppKey();
$applicationStoreId = $applicationData->getAppStoreid();
$storerooturl = $this->getStoreManager()->getStore($applicationStoreId)->getBaseUrl();
$myHelper = $this->helper('Mobicommerce\Mobiadmin3\Helper\Data');
$themename = $myHelper->getThemeName($applicationCode);
$version = $applicationData->getVersionType();
if(!in_array($version, ['001', '002']))
	$version = '001';
?>
<script>
require([
    "jquery",
    'Magento_Ui/js/modal/modal',
    "jquery/ui",
    "prototype",
    "extjs/ext-tree-checkbox",
    "mage/adminhtml/form",
    "mage/translate"
], function (jQuery, modal) {
});
</script>


<form target="_blank" name="buynow" id="buynow" action="<?php echo $myHelper->buyNowUrl($version); ?>" method="post">
    <input type="hidden" name="app_name" value="<?php echo $applicationName; ?>"/>
    <input type="hidden" name="app_preview_code" value="<?php echo $applicationKey; ?>"/>
    <input type="hidden" name="app_code" value="<?php echo $applicationCode; ?>"/>
    <?php if($version == '001'): ?>
    	<input type="hidden" name="selectedapp" value="nativeapps"/>
    <?php elseif($version == '002'): ?>
    	<input type="hidden" name="selectedapp" value="nativeapps-widget">
    	<input type="hidden" value="nativeapps-widget" name="selectedoptions">
    <?php endif; ?>
    <input type="hidden" name="store_rooturl" value="<?php echo $storerooturl; ?>"/>
</form>