<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->get('Magento\Customer\Model\Session');
    $iFrameUrl = $customerSession->getTelrPaymentUrl();

if($iFrameUrl != ''){
	$html = "<iframe id= 'telr' src= '" . $iFrameUrl . "' style='width: 100%; height:450px; border: none;'></iframe>";
}else{
	$html = 'Sorry, unable to process your transaction at this time. Please try again.';
}
echo $html;
?>
